server:
  port: ${SERVER_PORT:8080}

  jetty:
    accesslog:
      enabled: true
      retention-period: ${LOG_RETENTION_PERIOD:10}

aws:
  accessKey: key_1
  privateKey: key_private
  bucket: bucket_name